version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
  cache:
    image: redis:alpine
    container_name: cache
    ports:
      - 6379:6379
  shortner:
    build: .
    container_name: lilurl
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB_HOST=db
      - REDIS_HOST=cache
    depends_on:
      - db
      - cache

volumes:
  postgres_data_prod:
