version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

volumes:
  postgres_data_prod:

